create extension if not exists pgcrypto;

create table if not exists public.viral_ads (
  id text primary key,
  platform text not null,
  category text not null,
  title text not null,
  hook text not null,
  views bigint not null default 0,
  engagement numeric(5,2) not null default 0,
  velocity integer not null default 0 check (velocity between 0 and 100),
  conversion integer not null default 0 check (conversion between 0 and 100),
  cta text not null default '',
  tags text[] not null default '{}',
  product_match text not null default '',
  emotion text not null default '',
  structure text[] not null default '{}',
  source_url text,
  transcript text,
  screenshot_url text,
  scanned_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists viral_ads_platform_idx on public.viral_ads (platform);
create index if not exists viral_ads_category_idx on public.viral_ads (category);
create index if not exists viral_ads_velocity_idx on public.viral_ads (velocity desc);
create index if not exists viral_ads_scanned_at_idx on public.viral_ads (scanned_at desc);
create index if not exists viral_ads_tags_idx on public.viral_ads using gin (tags);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  score integer not null default 0 check (score between 0 and 100),
  angle text not null default '',
  shopify_product_id text,
  product_url text,
  image_url text,
  source text not null default 'manual',
  price numeric(10,2),
  ingredients text[] not null default '{}',
  benefits text[] not null default '{}',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists product_url text;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists source text not null default 'manual';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_shopify_product_id_key'
  ) then
    alter table public.products
      add constraint products_shopify_product_id_key unique (shopify_product_id);
  end if;
end $$;

create index if not exists products_active_category_idx on public.products (active, category);
create index if not exists products_score_idx on public.products (score desc);
create index if not exists products_shopify_product_id_idx on public.products (shopify_product_id);

create table if not exists public.creatives (
  id text primary key,
  status text not null default 'Draft' check (status in ('Ready', 'Review', 'Draft', 'Queued', 'Published')),
  product text not null,
  format text not null,
  hook text not null,
  asset text not null default '',
  channel text not null default '',
  score integer not null default 0 check (score between 0 and 100),
  approved boolean not null default false,
  export_payload jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists creatives_status_score_idx on public.creatives (status, score desc);
create index if not exists creatives_approved_idx on public.creatives (approved);

create table if not exists public.publishing_queue (
  id uuid primary key default gen_random_uuid(),
  channel text not null,
  publish_at timestamptz,
  display_time text,
  content text not null,
  status text not null default 'Draft',
  creative_id text references public.creatives (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists publishing_queue_publish_at_idx on public.publishing_queue (publish_at);
create index if not exists publishing_queue_status_idx on public.publishing_queue (status);

create table if not exists public.workflow_steps (
  id bigint generated by default as identity primary key,
  step_time text not null,
  title text not null,
  description text not null,
  sort_order integer not null
);

create index if not exists workflow_steps_sort_order_idx on public.workflow_steps (sort_order);

create table if not exists public.shopify_products (
  id text primary key,
  title text not null,
  handle text,
  vendor text,
  product_type text,
  status text,
  tags text,
  published_at timestamptz,
  image_url text,
  raw_data jsonb not null default '{}',
  synced_at timestamptz not null default now()
);

create index if not exists shopify_products_synced_at_idx on public.shopify_products (synced_at desc);
create index if not exists shopify_products_product_type_idx on public.shopify_products (product_type);
create index if not exists shopify_products_status_idx on public.shopify_products (status);

create table if not exists public.shopify_collections (
  id text primary key,
  title text not null,
  handle text,
  body_html text,
  published boolean,
  raw_data jsonb not null default '{}',
  synced_at timestamptz not null default now()
);

create index if not exists shopify_collections_synced_at_idx on public.shopify_collections (synced_at desc);

create table if not exists public.shopify_sessions (
  id text primary key,
  shop text not null,
  state text,
  is_online boolean not null default false,
  scope text,
  access_token text,
  expires timestamptz,
  online_access_info jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists shopify_sessions_shop_idx on public.shopify_sessions (shop);

-- ─────────────────────────────────────────────────────────────
-- PRODUCT VIRAL INTELLIGENCE TABLES
-- ─────────────────────────────────────────────────────────────

create table if not exists public.product_viral_memory (
  id                  uuid primary key default gen_random_uuid(),
  product_id          text not null unique,
  product_name        text not null,
  most_viral_ad_id    text,
  viral_score         integer not null default 0 check (viral_score between 0 and 100),
  hook                text not null default '',
  pacing              text not null default '',
  cta                 text not null default '',
  visual_style        text not null default '',
  emotional_triggers  text[] not null default '{}',
  structure           text[] not null default '{}',
  platform_breakdown  jsonb not null default '{}',
  last_updated        timestamptz not null default now(),
  reproduction_count  integer not null default 0,
  performance_metrics jsonb not null default '{"avg_views":0,"avg_engagement":0,"avg_conversion":0}',
  created_at          timestamptz not null default now()
);

create index if not exists product_viral_memory_product_id_idx  on public.product_viral_memory (product_id);
create index if not exists product_viral_memory_viral_score_idx on public.product_viral_memory (viral_score desc);
create index if not exists product_viral_memory_last_updated_idx on public.product_viral_memory (last_updated desc);

create table if not exists public.product_viral_alternatives (
  id                  uuid primary key default gen_random_uuid(),
  product_id          text not null,
  product_name        text not null,
  platform            text not null,
  source_url          text,
  hook                text not null default '',
  hook_score          integer not null default 0 check (hook_score between 0 and 100),
  pacing              text not null default '',
  pacing_score        integer not null default 0 check (pacing_score between 0 and 100),
  cta                 text not null default '',
  cta_score           integer not null default 0 check (cta_score between 0 and 100),
  visual_style        text not null default '',
  visual_style_score  integer not null default 0 check (visual_style_score between 0 and 100),
  emotional_triggers  text[] not null default '{}',
  structure           text[] not null default '{}',
  duration            text not null default '15s',
  aspect_ratio        text not null default '9:16',
  overall_score       integer not null default 0 check (overall_score between 0 and 100),
  found_at            timestamptz not null default now(),
  created_at          timestamptz not null default now()
);

create index if not exists product_viral_alternatives_product_id_idx   on public.product_viral_alternatives (product_id);
create index if not exists product_viral_alternatives_platform_idx      on public.product_viral_alternatives (platform);
create index if not exists product_viral_alternatives_overall_score_idx on public.product_viral_alternatives (overall_score desc);

create table if not exists public.product_viral_reproductions (
  id                   uuid primary key default gen_random_uuid(),
  product_id           text not null,
  product_name         text not null,
  creative_id          text references public.creatives (id) on delete set null,
  platform             text not null,
  hook_used            text not null default '',
  structure_used       text[] not null default '{}',
  viral_score_at_time  integer not null default 0,
  notes                text,
  performance_views    bigint,
  performance_engagement numeric(5,2),
  performance_conversion numeric(5,2),
  reproduced_at        timestamptz not null default now(),
  created_at           timestamptz not null default now()
);

create index if not exists product_viral_reproductions_product_id_idx   on public.product_viral_reproductions (product_id);
create index if not exists product_viral_reproductions_reproduced_at_idx on public.product_viral_reproductions (reproduced_at desc);
create index if not exists product_viral_reproductions_platform_idx      on public.product_viral_reproductions (platform);

alter table public.viral_ads enable row level security;
alter table public.products enable row level security;
alter table public.creatives enable row level security;
alter table public.publishing_queue enable row level security;
alter table public.workflow_steps enable row level security;
alter table public.shopify_products enable row level security;
alter table public.shopify_collections enable row level security;
alter table public.shopify_sessions enable row level security;
alter table public.evics_renders enable row level security;

drop policy if exists "dashboard read viral ads" on public.viral_ads;
drop policy if exists "dashboard read products" on public.products;
drop policy if exists "dashboard read creatives" on public.creatives;
drop policy if exists "dashboard read publishing queue" on public.publishing_queue;
drop policy if exists "dashboard read workflow steps" on public.workflow_steps;
drop policy if exists "dashboard read shopify products" on public.shopify_products;
drop policy if exists "dashboard read shopify collections" on public.shopify_collections;
drop policy if exists "dashboard read evics renders" on public.evics_renders;
drop policy if exists "dashboard write evics renders" on public.evics_renders;

create policy "dashboard read viral ads"
on public.viral_ads for select
to anon, authenticated
using (true);

create policy "dashboard read products"
on public.products for select
to anon, authenticated
using (active = true);

create policy "dashboard read creatives"
on public.creatives for select
to anon, authenticated
using (true);

create policy "dashboard read publishing queue"
on public.publishing_queue for select
to anon, authenticated
using (true);

create policy "dashboard read workflow steps"
on public.workflow_steps for select
to anon, authenticated
using (true);

create policy "dashboard read shopify products"
on public.shopify_products for select
to anon, authenticated
using (true);

create policy "dashboard read shopify collections"
on public.shopify_collections for select
to anon, authenticated
using (true);

-- ── Product Viral Intelligence RLS ──
alter table public.product_viral_memory        enable row level security;
alter table public.product_viral_alternatives  enable row level security;
alter table public.product_viral_reproductions enable row level security;

drop policy if exists "dashboard read product viral memory"        on public.product_viral_memory;
drop policy if exists "dashboard write product viral memory"       on public.product_viral_memory;
drop policy if exists "dashboard read product viral alternatives"  on public.product_viral_alternatives;
drop policy if exists "dashboard write product viral alternatives" on public.product_viral_alternatives;
drop policy if exists "dashboard read product viral reproductions" on public.product_viral_reproductions;
drop policy if exists "dashboard write product viral reproductions" on public.product_viral_reproductions;

create policy "dashboard read product viral memory"
on public.product_viral_memory for select
to anon, authenticated
using (true);

create policy "dashboard write product viral memory"
on public.product_viral_memory for all
to service_role
using (true);

create policy "dashboard read product viral alternatives"
on public.product_viral_alternatives for select
to anon, authenticated
using (true);

create policy "dashboard write product viral alternatives"
on public.product_viral_alternatives for all
to service_role
using (true);

create policy "dashboard read product viral reproductions"
on public.product_viral_reproductions for select
to anon, authenticated
using (true);

create policy "dashboard write product viral reproductions"
on public.product_viral_reproductions for all
to service_role
using (true);
